### ISSUE TITLE
NuParserv007.py run error

### ISSUE THREAD

**Issue by zhuchunyu** [JetJet13/NuExplorerOS#7]
Traceback (most recent call last):
  File "NuParserv007.py", line 1598, in <module>
    getparkrates = access.getparkrates(BCT.count()-1,"B")
  File "C:\Python27\lib\site-packages\bitcoinrpc\authproxy.py", line 141, in **call**
    raise JSONRPCException(response['error'])
bitcoinrpc.authproxy.JSONRPCException: -12: Error: Park rates not found

**Comment by huafei117** [comment]
pleas clone from latest version
